name: Lab Templates CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  ci:
    uses: Projet-technique-Altair/altair-ci/.github/workflows/lab-templates-ci.yml@main
